### ISSUE TITLE
Consider renaming this project - and have it renamed in Bower registry

### ISSUE THREAD

**Issue by JimAnkrom** [nathanfaucett/require.js#2]
This is the real require.js - http://requirejs.org/ - which you are currently squatting in the Bower registry by having your bower.json declare itself as require.js. Which would be fine if your library didn't actually attempt to provide require-like abilities... so you're potentially causing other developers lots of headache if they happen to 'bower install require.js' and not 'bower install requirejs' as they - without a doubt - intended.

FYI, this is pretty much the industry standard commonjs "node.js require" browser implementation:
http://browserify.org/

**Comment by OKNoah** [comment]
Darn, glad I read this cause I was confusing this for requirejs, I think.

**Comment by joacim-boive** [comment]
I just spent hours on this, not getting my code to work...

How is that rename coming? You're confusing a lot of devs...
